### ISSUE TITLE
Show how to create t2.large (script and aws.html)

### ISSUE THREAD

**Issue by jph00** [fastai/dlcert1#10]

**Comment by 0bserver07** [comment]
Do you want this to be video or just a written guide?
I can write the steps, if a written guide is preferred.

**Comment by jph00** [comment]
I think it's as simple as replacing 'p2' with 't2' in the setup script,
and making sure the setup script uses the correct instance type. So not
sure there's much to do here.


BTW If you have some time, we'd love help with creating time codes for
the other lessons - Taro has done 3 and 4, and is now working on 1.


Also, if you find common questions on the forum that aren't answered on
the lesson wiki pages, it would be great to do that too.


--

Jeremy Howard





On Mon, Dec 19, 2016, at 10:00 AM, Yad Faeq wrote:

> Do you want this to be video or just a written guide?

>  I can write the steps, if a written guide is preferred.



> — You are receiving this because you authored the thread. Reply to
> this email directly, view it on GitHub[1], or mute the thread[2].
> 




Links:

  1. https://github.com/fastai/dlcert1/issues/10#issuecomment-268032923

**Comment by 0bserver07** [comment]
Sounds good, I look into to those 2 other things.
