### ISSUE TITLE
Public readonly wiki access

### ISSUE THREAD

**Issue by jph00** [fastai/dlcert1#4]
Need to think about who to give write access to, and how

**Comment by 0bserver07** [comment]
I believe MediaWiki has some user-level authorization features:
[here](http://www.paulgu.com/wiki/How_do_I_allow_only_authorized_users_to_edit_pages)

Also here to show how to edit [options file](http://www.paulgu.com/wiki/How_do_I_allow_only_authorized_users_to_edit_pages)
