### ISSUE TITLE
Complete basic web-site

### ISSUE THREAD

**Issue by jph00** [fastai/dlcert1#5]
- [x] Finish about page
- [x] Create pages for each lesson
- [x] Add intro videos
- [x] Copy over key lesson info from wiki
- [x] Add testimonials
- [x] Add organization logos

**Comment by 0bserver07** [comment]
@jph00 Let me know if I can help with this:
Simple static sites can work and integrate easily with Markdown + Wikis:

I use [Jekyll](https://jekyllrb.com/), easily deploy able to S3 with or github-pages

**Comment by jph00** [comment]
@0bserver07 site is already being built in jekyll in this repo! see it at http://course.fast.ai
